#
# Generate _build_info.py from pyproject.toml + git state.
#
# Run during build: python -m btpay.generate_build_info
# Or automatically via the build command in deploy configs.
#
import subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def get_version():
    '''Read version from pyproject.toml (single source of truth).'''
    pyproject = ROOT / 'pyproject.toml'
    for line in pyproject.read_text().splitlines():
        if line.startswith('version'):
            # version = "0.1.1"
            return line.split('"')[1]
    return '0.0.0'


def get_git(cmd):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=5, cwd=ROOT)
        return r.stdout.strip() if r.returncode == 0 else ''
    except Exception:
        return ''


def main():
    version = get_version()
    commit = get_git(['git', 'rev-parse', '--short=12', 'HEAD'])
    branch = get_git(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])

    out = ROOT / 'btpay' / '_build_info.py'
    out.write_text(
        "# Auto-generated at build time — do not edit.\n"
        "# Regenerated by: python -m btpay.generate_build_info\n"
        "VERSION = %r\n"
        "GIT_COMMIT = %r\n"
        "GIT_BRANCH = %r\n" % (version, commit, branch)
    )
    print('btpay/_build_info.py: version=%s commit=%s branch=%s' % (version, commit, branch))


if __name__ == '__main__':
    main()

# EOF
